/* Ultimate Doom 1.9 */
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m1.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m2.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m3.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m4.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m5.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m6.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m7.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m8.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e1m9.zs"

#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m1.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m2.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m3.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m4.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m5.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m6.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m7.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e2m8.zs"

#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e3m3.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e3m4.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e3m5.zs"
#include "union_zscript/levels/monster_placement/iwads/ultimate_doom/e3m6.zs"