/* Ultimate Doom 1.9 */
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m1.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m2.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m3.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m4.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m5.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m6.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m7.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m8.zs"
#include "union_zscript/levels/reverbs/iwads/ultimate_doom/e1m9.zs"